---

name: "admin-password-test"

trigger: none

variables:
- group: build

pool:
  name: 'vmss-agent-pool-linux-001'


jobs:
  - job: test
    displayName: "Test Job"
    continueOnError: false

    steps:

      - checkout: self

      - script: |
          env
        displayName: Show environment variables

      - script: |
          source /etc/os-release
          printf "Running on: %s\n" "$PRETTY_NAME"
        displayName: Check operating system version

      - script: |
          echo "Build index: $(build_index)"
        displayName: Check build index

      - script: |
          docker --version || echo "Docker not found!"
        displayName: Check Docker
