---

name: "container-test"

trigger: none

variables:
- group: build
- name: containerImage
  value: "ghcr.io/tonyskidmore/azdo-container-image:latest"

pool:
  name: 'vmss-agent-pool-linux-006'

resources:
  containers:
    - container: ubuntu
      image: '${{ variables.containerImage }}'

jobs:
  - job: test
    displayName: "Test Container Job"
    continueOnError: false
    container: ubuntu

    steps:

      - checkout: self

      - script: |
          env
        displayName: Show environment variables

      - script: |
          source /etc/os-release
          printf "Running on: %s\n" "$PRETTY_NAME"
        displayName: Check operating system version

      - script: |
          sudo apt update > /dev/null 2>&1
          sudo apt install -y jq unzip > /dev/null 2>&1
          url=""http://169.254.169.254/metadata/instance?api-version=2021-02-01""
          metadata=$(curl -s \
                          -H Metadata:true \
                          --noproxy "*" \
                          "$url")
          jq <<< "$metadata"
        displayName: Metadata

      - script: |
          az login --identity
          az account show
          tenant_id=$(az account show --query 'tenantId' -o tsv)
          subscription_id=$(az account show --query 'id' -o tsv)
          echo "##vso[task.setvariable variable=SUB_ID]$subscription_id"
          echo "##vso[task.setvariable variable=TEN_ID]$tenant_id"
        displayName: Azure login

      - script: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
        displayName: Install Terraform

      - script: |
          tf_ver=$(terraform version -json | jq .terraform_version)
          printf "Terraform version installed: %s\n" "$tf_ver"
        displayName: Terraform version

      - script: |
          terraform init
          terraform plan
        workingDirectory: $(System.DefaultWorkingDirectory)/module/examples/006-managed_identity/terraform
        displayName: Terraform plan
        env:
          TF_IN_AUTOMATION: true
          ARM_USE_MSI: true
          ARM_SUBSCRIPTION_ID: $(SUB_ID)
          ARM_TENANT_ID: $(TEN_ID)
