# terrascan configuration file https://github.com/tenable/terrascan/blob/master/config/terrascan.toml

# scan and skip rules configuration
[rules]
    # skip rules (list of rules to skip)
    # ignore "Ensure that Azure Virtual Network subnet is configured with a Network Security Group"
    # simple admin_password example does not include a NSG assignment
    skip-rules = [
      "AC_AZURE_0389", # Ensure that Azure Resource Group has resource lock enabled
      "AC_AZURE_0356" # Ensure that Azure Virtual Network subnet is configured with a Network Security Group
    ]
[severity]
level = "high"
