# terrascan configuration file https://github.com/tenable/terrascan/blob/master/config/terrascan.toml

# scan and skip rules configuration
[rules]
    # scan rules (list of rules to scan, adding rules here will override rules in the policy path)
    # scan-rules = [
    #     "AWS.S3Bucket.DS.High.1043",
    #     "AWS.S3Bucket.IAM.High.0370"
    # ]

    # skip rules (list of rules to skip)
    # ignore "Ensure that Azure Virtual Network subnet is configured with a Network Security Group"
    # simple admin_password example does not include a NSG assignment
    skip-rules = [
      "AC_AZURE_0356"
    ]
