ado_pool_name            = "vmss-agent-pool-linux-002"
ado_project              = "demo-vmss"
ado_service_connection   = "demo-vmss"
vmss_name                = "vmss-agent-pool-linux-002"
vmss_resource_group_name = "rg-demo-azure-devops-vmss"
vmss_vnet_name           = "vnet-demo-azure-devops-vmss"
vmss_subnet_name         = "snet-demo-azure-devops-vmss"
